# Generated by Django 5.2.2 on 2025-06-09 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('Beaches & Relaxation', 'Beach'), ('Adventure & Sports', 'Sports'), ('Hiking & Nature', 'Hiking'), ('Entertainment & Nightlife', 'Entertainment'), ('Culture & History', 'Culture'), ('Shopping & Markets', 'Shopping'), ('Food & Dinning', 'Food'), ('Wellness & Spa', 'Wellness')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('destination', models.TextField(max_length=100)),
                ('trip_type', models.TextField(choices=[('SOLO', 'Solo'), ('FAMILY', 'Family'), ('FRIENDS', 'Friends'), ('PARTNER', 'Partner')], max_length=20)),
                ('mood', models.TextField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ROMANTIC', 'Romantic'), ('ADVENTUROUS', 'Adventurous'), ('RELAXED', 'Relaxed')], max_length=30)),
                ('plan', models.JSONField(blank=True, null=True)),
                ('spending_types', models.ManyToManyField(to='core.spending_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
