# Generated by Django 5.2.2 on 2025-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending_type',
            name='name',
            field=models.CharField(choices=[('Beach', 'Beaches & Relaxation'), ('Sports', 'Adventure & Sports'), ('Hiking', 'Hiking & Nature'), ('Entertainment', 'Entertainment & Nightlife'), ('Culture', 'Culture & History'), ('Shopping', 'Shopping & Markets'), ('Food', 'Food & Dining'), ('Wellness', 'Wellness & Spa')], max_length=100, unique=True),
        ),
    ]
