# Generated by Django 5.2.2 on 2025-06-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_spending_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='mood',
        ),
    ]
